# 공통적용
oauth:
  kakao:
    base-url: ${KAKAO_BASE_URL}
    client-id: ${KAKAO_CLIENT}
    client-secret: ${KAKAO_SECRET}
    redirect-url: ${KAKAO_REDIRECT}
    app-id : ${KAKAO_APP_ID}

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  s3:
    bucket: ${AWS_S3_BUCKET}
    base-url: ${AWS_S3_BASE_URL}
---
spring:
  config:
    activate:
      on-profile: dev
oauth:
  kakao:
    base-url: ${KAKAO_BASE_URL}
    client-id: ${KAKAO_CLIENT}
    client-secret: ${KAKAO_SECRET}
    redirect-url: ${KAKAO_REDIRECT}
    app-id : ${KAKAO_APP_ID}
---
spring:
  config:
    activate:
      on-profile: test

---
spring:
  config:
    activate:
      on-profile: staging

---
spring:
  config:
    activate:
      on-profile: prod