# 공통적용
aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  s3:
    bucket: ${AWS_S3_BUCKET}
    base-url: ${AWS_S3_BASE_URL}

spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}

---
spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    band.gosrock.infrastructure.outer.api.* : debug
---
spring:
  config:
    activate:
      on-profile: staging

---
spring:
  config:
    activate:
      on-profile: prod