# 공통적용
aws:
  access-key: ${AWS_ACCESS_KEY:testKey}
  secret-key: ${AWS_SECRET_KEY:secretKey}
  s3:
    bucket: ${AWS_S3_BUCKET:bucket}
    private-bucket : ${AWS_S3_BUCKET_PRIVATE:bucket-private}
    base-url: ${AWS_S3_BASE_URL:base-url}

spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}

slack:
  webhook:
    token: ${SLACK_WEBHOOK_TOKEN:}
    id: ${SLACK_WEBHOOK_ID:}
    service-alarm-channel :  ${SLACK_SERVICE_CHANNEL_ID:}
    username: ${SLACK_WEBHOOK_USERNAME:DuDoongBot}
    icon-url: ${SLACK_WEBHOOK_ICON_URL:}


---
spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    band.gosrock.infrastructure.outer.api.* : debug
---
spring:
  config:
    activate:
      on-profile: staging
logging:
  level:
    band.gosrock.infrastructure.outer.api.* : debug
---
spring:
  config:
    activate:
      on-profile: prod