auth:
  jwt:
    secret-key: ${JWT_SECRET_KEY:testkeytestkeytestkeytestkeytestkeytestkeytestkeytestkeytestkey}
    access-exp: ${JWT_ACCESS_EXP:3600}
    refresh-exp: ${JWT_REFRESH_EXP:3600}

oauth:
  kakao:
    base-url: ${KAKAO_BASE_URL}
    client-id: ${KAKAO_CLIENT}
    client-secret: ${KAKAO_SECRET}
    redirect-url: ${KAKAO_REDIRECT}
    app-id: ${KAKAO_APP_ID}