auth:
  local:
    jwt:
      secretKey: ${JWT_SECRET_KEY:testkeytestkeytestkeytestkeytestkeytestkeytestkeytestkeytestkey}
      accessExp: ${JWT_ACCESS_EXP:3600}
      refreshExp: ${JWT_REFRESH_EXP:3600}