version: '3.7'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  mysql:
    image: 'mysql:8.4'
    ports:
      - '13306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: dudoong
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: dudoong
      MYSQL_USER: dudoong
      MYSQL_PASSWORD: dudoong
    volumes:
      - dudoong-mysql-data:/var/lib/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-time-zone=+09:00
      --mysql-native-password=ON

volumes:
  dudoong-mysql-data:
