# commons
spring:
  profiles:
    include:
      - infrastructure
      - domain
  jackson:
    property-naming-strategy: SNAKE_CASE

springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: test

---
spring:
  config:
    activate:
      on-profile: staging

---
spring:
  config:
    activate:
      on-profile: prod