# commons
spring:
  profiles:
    include:
      - infrastructure
      - domain
      - common
  jackson:
    property-naming-strategy: SNAKE_CASE
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

---
spring:
  config:
    activate:
      on-profile: dev
#logging:
#  level:
#    root: info
---
spring:
  config:
    activate:
      on-profile: staging

---
spring:
  config:
    activate:
      on-profile: prod