# commons
spring:
  profiles:
    include:
      - infrastructure
      - domain
      - common
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
server:
  forward-headers-strategy: framework
---
spring:
  config:
    activate:
      on-profile: dev
#logging:
#  level:
#    root: info
#logging:
#  level:
#    org.springframework.data.*.*: debug
#    org.springframework.cache.*: debug
---
spring:
  config:
    activate:
      on-profile: staging

---
spring:
  config:
    activate:
      on-profile: prod