# commons
spring:
  profiles:
    include:
      - infrastructure
      - domain
      - common

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: staging

---
spring:
  config:
    activate:
      on-profile: prod