spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/dudoong?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maxLifetime: 580000
      maximum-pool-size: 10
    username: dudoong
    password: dudoong
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    sql:
      init:
        mode: always
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
