name: Build Batch Server
on:
  push:
    tags:
      - Batch-v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17 ]
    outputs:
      version: ${{ steps.get_version.outputs.BRANCH_NAME }}

    steps:
      - name: Check Out The Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'corretto'

      - name: Get the version
        id: get_version
        run: |
          RELEASE_VERSION_WITHOUT_V="$(cut -d'v' -f2 <<< ${GITHUB_REF#refs/*/})"
          echo ::set-output name=VERSION::$RELEASE_VERSION_WITHOUT_V 

      #테스트 수행용 도커 컴포즈
      - name: Start containers
        run: docker-compose up -d

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew :DuDoong-Batch:build --no-daemon

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./DuDoong-Batch
          push: true
          tags: |
            water0641/dudoong-batch:${{ steps.get_version.outputs.VERSION }}
            water0641/dudoong-batch:latest

